---
name: temurin-jdk-17
description: |
  Eclipse Temurin is the open source Java SE build based upon OpenJDK.
  Temurin is available for a wide range of platforms and Java SE versions.
homepage: https://github.com/eclipse/eclipse.jdt.ls
licenses:
  - GPL-2.0
languages:
  - Java
categories:
  - Runtime

source:
  id: pkg:generic/java/temurin@17.0.15+6
  download:
    - target: darwin_arm64
      files:
        openjdk-17.0.15.tar.gz: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.15%2B6/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.15_6.tar.gz
      bin: jdk-17.0.15+6/Contents/Home/bin/java

    - target: darwin_x64
      files:
        openjdk-17.0.15.tar.gz: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.15%2B6/OpenJDK17U-jdk_x64_mac_hotspot_17.0.15_6.tar.gz
      bin: jdk-17.0.15+6/Contents/Home/bin/java

    - target: linux_x64
      files:
        openjdk-17.0.15.tar.gz: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.15%2B6/OpenJDK17U-jdk_x64_linux_hotspot_17.0.15_6.tar.gz
      bin: jdk-17.0.15+6/bin/java

    - target: linux_arm64
      files:
        openjdk-17.0.15.tar.gz: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.15%2B6/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.15_6.tar.gz
      bin: jdk-17.0.15+6/bin/java

    - target: win
      files:
        openjdk-17.0.15.zip: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.15%2B6/OpenJDK17U-jdk_x64_windows_hotspot_17.0.15_6.zip
      bin: jdk-17.0.15+6/bin/java.exe

bin:
  java: "{{source.download.bin}}"
