---
name: temurin-jdk-8
description: |
  Eclipse Temurin is the open source Java SE build based upon OpenJDK.
  Temurin is available for a wide range of platforms and Java SE versions.
homepage: https://adoptium.net/temurin/releases
licenses:
  - GPL-2.0
languages:
  - Java
categories:
  - Runtime

source:
  id: pkg:generic/java/temurin@8.0.452+9
  download:
    - target: [darwin_x64, darwin_arm64]
      files:
        openjdk-8.0.452.tar.gz: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u452-b09/OpenJDK8U-jdk_x64_mac_hotspot_8u452b09.tar.gz
      content: jdk8u452-b09/Contents/Home/

    - target: linux_x64
      files:
        openjdk-8.0.452.tar.gz: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u452-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u452b09.tar.gz
      content: jdk8u452-b09/

    - target: linux_arm64
      files:
        openjdk-8.0.452.tar.gz: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u452-b09/OpenJDK8U-jdk_aarch64_linux_hotspot_8u452b09.tar.gz
      content: jdk8u452-b09/

    - target: win
      files:
        openjdk-8.0.452.zip: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u452-b09/OpenJDK8U-jdk_x64_windows_hotspot_8u452b09.zip
      content: jdk8u452-b09/

opt:
  jdk/temurin/8/: "{{source.download.content}}"
