---
name: temurin-jdk-21
description: |
  Eclipse Temurin is the open source Java SE build based upon OpenJDK.
  Temurin is available for a wide range of platforms and Java SE versions.
homepage: https://adoptium.net/temurin/releases
licenses:
  - GPL-2.0
languages:
  - Java
categories:
  - Runtime

source:
  id: pkg:generic/java/temurin@21.0.7+6
  download:
    - target: darwin_arm64
      files:
        openjdk-21.0.7.tar.gz: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_aarch64_mac_hotspot_21.0.7_6.tar.gz
      content: jdk-21.0.7+6/Contents/Home/

    - target: darwin_x64
      files:
        openjdk-21.0.7.tar.gz: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_mac_hotspot_21.0.7_6.tar.gz
      content: jdk-21.0.7+6/Contents/Home/

    - target: linux_x64
      files:
        openjdk-21.0.7.tar.gz: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz
      content: jdk-21.0.7+6/

    - target: linux_arm64
      files:
        openjdk-21.0.7.tar.gz: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.7_6.tar.gz
      content: jdk-21.0.7+6/

    - target: win
      files:
        openjdk-21.0.7.zip: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_windows_hotspot_21.0.7_6.zip
      content: jdk-21.0.7+6/

opt:
  jdk/temurin/21/: "{{source.download.content}}"
