---
name: temurin-jdk-11
description: |
  Eclipse Temurin is the open source Java SE build based upon OpenJDK.
  Temurin is available for a wide range of platforms and Java SE versions.
homepage: https://adoptium.net/temurin/releases
licenses:
  - GPL-2.0
languages:
  - Java
categories:
  - Runtime

source:
  id: pkg:generic/java/temurin@11.0.27+6
  download:
    - target: darwin_arm64
      files:
        openjdk-11.0.27.tar.gz: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.27_6.tar.gz
      content: jdk-11.0.27+6/Contents/Home/

    - target: darwin_x64
      files:
        openjdk-11.0.27.tar.gz: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_x64_mac_hotspot_11.0.27_6.tar.gz
      content: jdk-11.0.27+6/Contents/Home/

    - target: linux_x64
      files:
        openjdk-11.0.27.tar.gz: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_x64_linux_hotspot_11.0.27_6.tar.gz
      content: jdk-11.0.27+6/

    - target: linux_arm64
      files:
        openjdk-11.0.27.tar.gz: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.27_6.tar.gz
      content: jdk-11.0.27+6/

    - target: win
      files:
        openjdk-11.0.27.zip: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.27%2B6/OpenJDK11U-jdk_x64_windows_hotspot_11.0.27_6.zip
      content: jdk-11.0.27+6/

opt:
  jdk/temurin/11/: "{{source.download.content}}"
